apiVersion: v1 
kind: Pod 
metadata:
 name: postgres 
 labels:
  name: postgres-app-pod
  app: demo-voting-app
spec: 
 containers:
 - name: postgres
   image: postgres:9.4
   ports:
   - containerPort: 5432
---
apiVersion: v1 
kind: Service 
metdata:
 name: postgres-service
 lables:
  name: 
  app: demo-voting-app
spec: 
 type: CluseterIP
 ports:
 - port: 5432
   targetPort: 5432
 selectors:
  name: postgres-app-pod
  app: demo-voting-app
   