apiVersion: v1 
kind: Pod 
metadata:
 name: redis 
 labels:
  name: redis-app-pod
  app: demo-voting-app
spec: 
 containers:
 - name: redis
   image: redis
   ports:
   - containerPort: 6379
---
apiVersion: v1 
kind: Service 
metdata:
 name: redis-service
 lables:
  name: 
  app: demo-voting-app
spec: 
 type: CluseterIP
 ports:
 - port: 6379
   targetPort: 6379
 selectors:
  name: redis-app-pod
  app: demo-voting-app
  