apiVersion: v1 
kind: Pod 
metadata:
 name: result-app-pod
 lables:
  name: result-app-pod
  app: demo-voting-app
spec:
 containers:
  - name: nodejs
    image: dockersamples/examplevotingapp_result
    ports:
    - containerPort: 80
---
apiVersion: v1 
kind: Service 
metdata:
 name: resultapp-service
  app: demo-voting-app
spec: 
  type: LoadBalancer
  selectors:
  name: result-app-pod
  app: demo-voting-app
  ports: 
  - port: 80
    targetPort: 80
---
apiVersion: v1 
kind: Service 
metdata:
 name: resultapp-service
  app: demo-voting-app
spec: 
  type: LoadBalancer
  selectors:
    name: result-app-pod
    app: demo-voting-app
  ports: 
  - port: 80
    targetPort: 80