apiVersion: v1 
kind: Pod 
metadata:
 name: voting-app-pod
 lables:
  name: voting-app-pod
  app: demo-voting-app
spec:
 containers:
  - name: python
    image: dockersamples/examplevotingapp_vote
    ports:
    - containerPort: 80
---
apiVersion: v1 
kind: Service 
metdata:
 name: voting-service
  app: demo-voting-app
spec: 
  type: LoadBalancer
  selectors:
   name: redis-app-pod
   app: demo-voting-app
  ports: 
  - port: 80
    targetPort: 80